import type { Lesson } from './schema';

export const demoLesson: Lesson = {
  title: 'Mediální mise',
  language: 'cs',
  subtitle: 'Jak přežít internet a neztratit důstojnost',
  audience: '1. ročník Digitální marketing',
  totalMinutes: 180,
  groupSize: '3–4 studenti',
  learningObjectives: [
    'Rozlišit médium, platformu, zdroj a autora.',
    'Vysvětlit framing, gatekeeping a agenda-setting.',
    'Rozlišit fakt, názor, interpretaci a reklamní tvrzení.',
    'Posoudit komerční zájem, algoritmickou selekci a důvěryhodnost zdroje.',
  ],
  blocks: [
    { id: 'b1', type: 'team_task', title: 'Co je sakra médium?', durationMinutes: 15, instructions: 'Rozdělte kartičky na médium, platformu, zdroj a tvůrce. Dva sporné případy musíte obhájit.', items: ['TikTok', 'CNN', 'influencer', 'tisková zpráva', 'ChatGPT', 'algoritmus Instagramu'], teacherNote: 'Debrief: odděl zdroj, autora, distribuční platformu a algoritmický výběr.', points: 4 },
    { id: 'b2', type: 'team_task', title: 'Redakce z pekla', durationMinutes: 25, instructions: 'Vyberte tři zprávy, určete pořadí a napište titulky. Máte bulvár a potřebujete KLIKY. Bonusový bod za nejhorší titulek, který je stále technicky pravdivý.', items: ['Ekonomika +1,8 %', 'Utekl páv', 'Firma propustí 2000 lidí', 'Brambora připomíná Karla Gotta', 'Nový výzkum Alzheimerovy choroby', 'Influencer spadl do bazénu'], teacherNote: 'Pojmy: gatekeeping, news values, agenda-setting.', points: 6 },
    { id: 'b3', type: 'team_task', title: 'Stejná událost, čtyři reality', durationMinutes: 25, instructions: 'Město ruší 120 parkovacích míst kvůli cyklopruhům. Vytvořte titulek, první dvě věty, popis fotografie a člověka, kterého oslovíte podle role svého média.', items: ['Motoristický web', 'Ekologický magazín', 'Lokální neutrální médium', 'Instagram politika, který změnu prosadil'], teacherNote: 'Pojem: framing. Zdůrazni, že různé rámce mohou pracovat se stejnými pravdivými fakty.', points: 5 },
    { id: 'b4', type: 'poll', title: 'Fakt, názor, nebo marketingový výpotek?', durationMinutes: 15, instructions: 'Zařaďte tvrzení „Češi milují slevy.“ Co přesně bychom potřebovali vědět, abychom ho mohli posoudit?', options: ['Fakt', 'Názor', 'Interpretace', 'Nelze určit bez definice'], teacherNote: 'Nejdůležitější je donutit studenty definovat vágní slovo „milují“.' },
    { id: 'b5', type: 'ranking', title: 'Influencer, nebo reklamní plocha?', durationMinutes: 25, instructions: 'Seřaďte případy od nejvíc redakčního obsahu po nejvíc komerčně motivovaný obsah. U tří položek vysvětlete, kdo má ekonomický zájem a jak je označen.', items: ['Recenze bez spolupráce', 'Produkt zdarma bez honoráře', '#spoluprace', 'Partner content', 'Článek na e-shopu: 5 nejlepších notebooků'], teacherNote: 'Pojmy: native advertising, advertorial, sponzorovaný obsah, product placement.', points: 5 },
    { id: 'b6', type: 'team_task', title: 'Algoritmus, který vám zničí život', durationMinutes: 25, instructions: 'Jste doporučovací algoritmus. Kevin začal videem „Jak začít posilovat“. Ve třech kolech mu navrhněte stále extrémnější obsah tak, aby každý krok byl algoritmicky obhajitelný.', teacherNote: 'Pojmy: engagement, personalizace, recommender system, algoritmická selekce, filter bubble.', points: 6 },
    { id: 'b7', type: 'reveal', title: 'Mediální CSI: kdo to vlastně řekl?', durationMinutes: 25, instructions: 'Zpráva tvrdí: „Lidé, kteří pijí tři kávy denně, jsou o 27 % produktivnější.“ Nejdřív navrhněte, co byste ověřovali. Pak odhalte původ informace.', revealText: 'DailyNews.cz → LifestyleToday → „britští vědci“ → průzkum výrobce kávy CoffeeLife. 27 % nebyl růst produktivity, ale rozdíl v subjektivní odpovědi mezi skupinami.', teacherNote: 'Pojmy: primární a sekundární zdroj, nezávislé potvrzení, source laundering.', points: 6 },
    { id: 'b8', type: 'team_task', title: 'BOSS FIGHT: Generace Z opouští vysoké školy!', durationMinutes: 20, instructions: 'Rozpitvejte fiktivní článek: „63 % mladých už nevěří, že má vysoká škola smysl.“ Článek vznikl ve spolupráci s dvanáctitýdenní vzdělávací akademií. Každý zásah musí mít formu: „Tohle je problém, protože…“ + správný pojem.', items: ['zdroj průzkumu', '63 % koho?', 'framing', 'komerční zájem', 'expert', 'influencer', 'algoritmická distribuce'], teacherNote: 'Finále: boduj jen obhájené zásahy, ne pouhé „tohle je divné“.', points: 10 },
    { id: 'b9', type: 'exit_ticket', title: 'Jedna otázka na cestu', durationMinutes: 5, instructions: 'Doplňte jednu větu: „Odteď se u mediálního sdělení nejdřív zeptám…“', teacherNote: 'Ideální reflex: Kdo to říká? Odkud to ví? Proč mi to říká? Co vybral a co vynechal?' },
  ],
};


export const demoLessonEn: Lesson = {
  title: 'Media Mission',
  subtitle: 'How to survive the internet without losing your judgement',
  audience: 'First-year Digital Marketing students',
  totalMinutes: 90,
  groupSize: '3–4 students',
  language: 'en',
  learningObjectives: [
    'Distinguish a medium, platform, source and author.',
    'Explain framing, gatekeeping and agenda-setting.',
    'Separate fact, opinion, interpretation and advertising claims.',
    'Assess commercial interests, algorithmic selection and source credibility.',
  ],
  blocks: [
    {
      id: 'en-b1',
      type: 'poll',
      title: 'Trust at first sight',
      durationMinutes: 10,
      instructions: 'Which signal would make you trust an online claim first? Choose one and be ready to explain why.',
      options: ['Named author', 'Primary source', 'Many shares', 'Professional design'],
      teacherNote: 'Use the spread of answers to open a discussion about credibility signals.',
    },
    {
      id: 'en-b2',
      type: 'team_task',
      title: 'The newsroom from hell',
      durationMinutes: 20,
      instructions: 'Choose three stories, put them in publication order and write a headline for each. Your goal is maximum clicks without making a technically false claim.',
      items: ['Economy grows by 1.8%', 'Peacock escapes from a park', 'Company cuts 2,000 jobs', 'New Alzheimer research', 'Influencer falls into a pool'],
      teacherNote: 'Connect choices to news values, gatekeeping and agenda-setting.',
      points: 6,
    },
    {
      id: 'en-b3',
      type: 'ranking',
      title: 'Rank the credibility signals',
      durationMinutes: 20,
      instructions: 'Rank all items from strongest to weakest credibility signal. Then justify your ranking in 1–2 sentences.',
      items: ['Primary evidence', 'Named expert with relevant expertise', 'Transparent methodology', 'Large number of shares', 'Polished visual design'],
      teacherNote: 'Ask what each signal can and cannot prove.',
      points: 5,
    },
    {
      id: 'en-b4',
      type: 'team_task',
      title: 'One event, four realities',
      durationMinutes: 20,
      instructions: 'A city removes 120 parking spaces to build cycle lanes. Create a headline and two opening sentences for your assigned outlet. Then identify what your framing emphasizes and leaves out.',
      items: ['Motoring website', 'Environmental magazine', 'Local neutral news outlet', 'Politician who supported the change'],
      teacherNote: 'Different frames can use the same true facts while producing very different impressions.',
      points: 5,
    },
    {
      id: 'en-b5',
      type: 'exit_ticket',
      title: 'One question to take away',
      durationMinutes: 20,
      instructions: 'Complete this sentence: “From now on, when I see a media claim, the first thing I will ask is…” Then add one sentence explaining why.',
      teacherNote: 'Look for source, evidence, motive, selection and omitted context.',
    },
  ],
};
