export const TERMS_PLAN_PRICING_CLAUSE = {
  cs: 'Aktuální obsah tarifů, jejich ceny, měna, fakturační období a limity jsou uvedeny v Ceníku a znovu v objednávkovém procesu před vznikem povinnosti platit. Tyto údaje mají být vzájemně konzistentní. Potvrzení objednávky, faktura ani jiný následný platební doklad již sjednané podmínky jednostranně nemění. Pokud se u spotřebitele předsmluvní údaje liší a jejich změna nebyla před uzavřením smlouvy výslovně sjednána způsobem vyžadovaným zákonem, použije se údaj pro spotřebitele příznivější.',
  en: 'Current plan features, prices, currency, billing period and allowances are shown on the Pricing page and again in the ordering flow before the user incurs an obligation to pay. These details are intended to be consistent. An order confirmation, invoice or other later payment document does not unilaterally change the terms already agreed. If pre-contract information presented to a consumer differs and the change was not expressly agreed before the contract was concluded in the manner required by law, the information more favourable to the consumer applies.',
} as const;

export const TERMS_WITHDRAWAL_CLAUSE = {
  cs: 'Požádáte-li výslovně o zahájení služby před uplynutím lhůty pro odstoupení a byli jste předem poučeni o poměrné úhradě, při následném spotřebitelském odstoupení se úhrada vypočte z celkové sjednané ceny zaplaceného období podle poměru skutečně uplynulé doby poskytování služby do doručení odstoupení k délce tohoto období. Počítá se skutečný čas, nikoli každý započatý den; u ročního tarifu je základem celé roční období. Poměrná úhrada se zaokrouhluje dolů na nejmenší měnovou jednotku. Počet AI operací ani vyčerpání kvóty výši úhrady nebo vratky nezvyšují. Bez doložené výslovné žádosti nebo předchozího poučení poměrnou úhradu nepožadujeme. Zbytek zaplacené ceny vrátíme stejným platebním prostředkem, se zohledněním již vrácených částek. Případná změna tarifu se posuzuje podle doložených sjednaných cen, plateb a časových období, nikoli podle aktuálního ceníku. Zákonná práva spotřebitele zůstávají zachována.',
  en: 'If you expressly request that the service start before the withdrawal period expires and were informed in advance about the proportionate charge, upon consumer withdrawal the charge is calculated from the total agreed price of the paid period in proportion to the actual time the service was supplied until receipt of the withdrawal notice, divided by the length of that paid period. Actual elapsed time is used, without charging each started day; an annual plan uses the full annual period. The retained charge is rounded down to the smallest currency unit. AI operations and exhausted allowances do not increase the charge or reduce the refund. Without evidence of the express request or prior information, no proportionate charge is retained. The remaining paid price is returned using the original payment method, taking previous refunds into account. Any plan change is assessed using the documented agreed prices, payments and time periods, rather than the current price list. Statutory consumer rights remain unaffected.',
} as const;
