export const TERMS_PLAN_PRICING_CLAUSE = {
  cs: 'Aktuální obsah tarifů, jejich ceny, měna, fakturační období a limity jsou uvedeny v Ceníku a znovu v objednávkovém procesu před vznikem povinnosti platit. Tyto údaje mají být vzájemně konzistentní. Potvrzení objednávky, faktura ani jiný následný platební doklad již sjednané podmínky jednostranně nemění. Pokud se u spotřebitele předsmluvní údaje liší a jejich změna nebyla před uzavřením smlouvy výslovně sjednána způsobem vyžadovaným zákonem, použije se údaj pro spotřebitele příznivější.',
  en: 'Current plan features, prices, currency, billing period and allowances are shown on the Pricing page and again in the ordering flow before the user incurs an obligation to pay. These details are intended to be consistent. An order confirmation, invoice or other later payment document does not unilaterally change the terms already agreed. If pre-contract information presented to a consumer differs and the change was not expressly agreed before the contract was concluded in the manner required by law, the information more favourable to the consumer applies.',
} as const;

export const TERMS_WITHDRAWAL_CLAUSE = {
  cs: 'Požádáte-li výslovně o zahájení služby před uplynutím lhůty pro odstoupení a byli jste předem poučeni o poměrné úhradě, při následném spotřebitelském odstoupení se úhrada vypočte z celkové sjednané ceny zaplaceného období podle poměru skutečně uplynulé doby poskytování služby do doručení odstoupení k délce tohoto období. Počítá se skutečný čas, nikoli každý započatý den; u ročního tarifu je základem celé roční období. Poměrná úhrada se zaokrouhluje dolů na nejmenší měnovou jednotku. Počet AI operací ani vyčerpání kvóty výši úhrady nebo vratky nezvyšují. Bez doložené výslovné žádosti nebo předchozího poučení poměrnou úhradu nepožadujeme. Zbytek zaplacené ceny vrátíme stejným platebním prostředkem, se zohledněním již vrácených částek. Případná změna tarifu se posuzuje podle doložených sjednaných cen, plateb a časových období, nikoli podle aktuálního ceníku. Zákonná práva spotřebitele zůstávají zachována.',
  en: 'If you expressly request that the service start before the withdrawal period expires and were informed in advance about the proportionate charge, upon consumer withdrawal the charge is calculated from the total agreed price of the paid period in proportion to the actual time the service was supplied until receipt of the withdrawal notice, divided by the length of that paid period. Actual elapsed time is used, without charging each started day; an annual plan uses the full annual period. The retained charge is rounded down to the smallest currency unit. AI operations and exhausted allowances do not increase the charge or reduce the refund. Without evidence of the express request or prior information, no proportionate charge is retained. The remaining paid price is returned using the original payment method, taking previous refunds into account. Any plan change is assessed using the documented agreed prices, payments and time periods, rather than the current price list. Statutory consumer rights remain unaffected.',
} as const;

export const TERMS_SERVICE_CHANGE_CLAUSE = {
  cs: [
    'Syllonaut může průběžně měnit digitální službu nad rámec změn nezbytných k zachování její bezvadnosti pouze bez dodatečných nákladů pro uživatele a ze spravedlivého důvodu. Takovým důvodem může být zejména bezpečnost, splnění právní povinnosti, zachování technické kompatibility, významná změna dodavatele nebo infrastruktury, přizpůsobení počtu uživatelů nebo prokazatelné zlepšení služby.',
    'Změny se před uplatněním klasifikují jako nezbytné bezpečnostní či opravné aktualizace, příznivé nebo jen nevýznamné změny, anebo změny zhoršující přístup ke službě či její užívání nikoli jen nevýznamně. U poslední skupiny Syllonaut přednostně zachová sjednanou verzi nejméně do konce již zaplaceného období a, je-li to bezpečné a technicky možné, umožní její další používání bez dodatečných nákladů.',
    'Nelze-li původní bezvadnou verzi bezpečně a technicky zachovat, dostane spotřebitel v přiměřené době před účinností změny, standardně alespoň 30 dnů předem, jasné oznámení e-mailem na trvalém nosiči. Oznámení uvede povahu a spravedlivý důvod změny, konkrétní dopad, okamžik účinnosti a právo závazek bez postihu vypovědět. Toto právo lze uplatnit do 30 dnů od doručení oznámení nebo od provedení změny, podle toho, co nastane později. Při ukončení se bez poplatku vrátí nevyužitá část předem zaplaceného období původním platebním prostředkem, není-li výslovně dohodnuto jinak bez nákladů pro spotřebitele.',
    'Právo ukončit smlouvu a spravovat vypnutí obnovení zůstává dostupné bez přijetí nových podmínek. Vyžaduje-li samotná změna smlouvy nový souhlas, Syllonaut si jej vyžádá dříve, než bude změna pro daného uživatele závazná.',
  ],
  en: [
    'Syllonaut may modify the digital service beyond changes necessary to keep it in conformity only without additional cost to the user and for a valid reason. Valid reasons may include security, compliance with legal obligations, maintaining technical compatibility, a material supplier or infrastructure change, adapting to increased user numbers, or a demonstrable service improvement.',
    'Before release, changes are classified as necessary security or conformity updates, beneficial or only minor changes, or changes that negatively affect access to or use of the service in more than a minor way. For the last category, Syllonaut will by default preserve the agreed version at least until the end of the already-paid period and, where safe and technically possible, allow continued use of the unchanged conforming version without additional cost.',
    'Where the original conforming version cannot safely and technically be maintained, a consumer will receive clear notice by email on a durable medium reasonably in advance, ordinarily at least 30 days before the change takes effect. The notice will state the nature and valid reason for the change, its specific impact, its effective time, and the right to terminate without penalty. That right may be exercised within 30 days after receipt of the notice or implementation of the change, whichever is later. On termination, the unused part of a prepaid period will be reimbursed without a fee using the original payment method unless the consumer expressly agrees otherwise without incurring costs.',
    'The right to terminate and to turn off renewal remains available without accepting new Terms. Where the contractual change itself requires renewed consent, Syllonaut will request it before the change becomes binding on the relevant user.',
  ],
} as const;

// LEGAL-016: account deletion never leaves a paid renewal running.
export const TERMS_ACCOUNT_DELETION_CLAUSE = {
  cs: [
    'Uživatel může přestat službu používat a požádat o zrušení účtu. Má-li účet aktivní placený tarif s automatickým obnovením, Syllonaut před zrušením účtu automatické obnovení sám ukončí, takže po zrušení účtu již nedojde k další platbě; uživatel je nemusí předem rušit sám. Zrušení účtu Syllonaut potvrdí e-mailem.',
    'Před zrušením účtu Syllonaut uživatele upozorní, že zrušením účtu zanikne přístup i ke zbývající části již zaplaceného období, a nabídne mu možnost ponechat účet do konce tohoto období. Tím nejsou dotčena zákonná práva spotřebitele, zejména právo odstoupit od smlouvy podle článku 7 a práva podle článku 10.',
    'Je-li uživatel vlastníkem školní organizace, zrušení jeho účtu samo neukončuje licenci organizace. Syllonaut před zrušením účtu zajistí předání vlastnictví organizace jinému správci, nebo na žádost organizace ukončí automatické obnovení školní licence.',
  ],
  en: [
    'A user may stop using the service and request account deletion. If the account has an active paid plan with automatic renewal, Syllonaut itself ends automatic renewal before deleting the account, so no further payment is taken after deletion; the user does not need to cancel it first. Syllonaut confirms the deletion by email.',
    'Before deleting the account, Syllonaut informs the user that deletion also ends access to any remaining part of an already paid period and offers to keep the account until the end of that period. This does not affect statutory consumer rights, in particular the right of withdrawal under section 7 and the rights under section 10.',
    'If the user owns a school organisation, deleting their account does not by itself end the organisation licence. Before deleting the account, Syllonaut arranges the transfer of organisation ownership to another administrator or, at the organisation’s request, ends automatic renewal of the school licence.',
  ],
} as const;

// LEGAL-017: evidenced complaint process with written receipt and resolution.
export const TERMS_COMPLAINT_CLAUSE = {
  cs: [
    'Pokud služba neodpovídá smlouvě nebo nefunguje, může uživatel uplatnit reklamaci online na stránce Reklamace (syllonaut.com/cs/complaint), e-mailem na vaclav@syllonaut.com nebo poštou na adresu poskytovatele. V reklamaci popište vadu, použitý účet, okolnosti chyby a požadovaný způsob vyřízení, bez zbytečných osobních údajů studentů.',
    'Syllonaut uživateli bezodkladně písemně potvrdí, kdy reklamaci uplatnil, co je jejím obsahem a jaký způsob vyřízení požaduje. Reklamaci vyřídí bez zbytečného odkladu, nejpozději do 30 dnů od jejího uplatnění, a písemně potvrdí datum a způsob vyřízení; zamítnutí písemně odůvodní. Zákonná práva z vadného plnění a zvláštní práva spotřebitelů k digitálním službám zůstávají zachována.',
  ],
  en: [
    'If the service does not conform to the contract or fails to work, a user may submit a complaint online on the Complaint page (syllonaut.com/en/complaint), by email to vaclav@syllonaut.com or by post to the provider address. Describe the defect, the account used, the circumstances and the requested remedy, without unnecessary student personal data.',
    'Syllonaut promptly confirms in writing when the complaint was submitted, what it contains and which remedy is requested. It resolves the complaint without undue delay and no later than 30 days after submission, and confirms the date and manner of resolution in writing; a rejection is justified in writing. Statutory rights relating to defective performance and consumer rights for digital services remain unaffected.',
  ],
} as const;

// LEGAL-018: technical requirements are pre-contractual information and part of the contract.
export const TERMS_TECHNICAL_REQUIREMENTS_CLAUSE = {
  cs: 'Služba se používá ve webovém prohlížeči. Technické požadavky na funkčnost, kompatibilitu a interoperabilitu (podporované prohlížeče a zařízení, cookies a úložiště prohlížeče, připojení k internetu a formáty souborů) jsou uvedeny na stránce Technické požadavky (syllonaut.com/cs/requirements) a u individuální placené objednávky jsou také součástí potvrzení smluvních informací. Nesoulad služby způsobený výlučně tím, že digitální prostředí uživatele těmto požadavkům neodpovídá, není vadou služby, byl-li uživatel o požadavcích jasně informován před uzavřením smlouvy. Požadavky lze změnit pouze postupem podle článku 10.',
  en: 'The service is used in a web browser. Technical requirements for functionality, compatibility and interoperability (supported browsers and devices, cookies and browser storage, internet connection and file formats) are set out on the Technical requirements page (syllonaut.com/en/requirements) and, for an individual paid order, also form part of the contract information confirmation. A lack of conformity caused solely by the user’s digital environment not meeting these requirements is not a defect of the service, provided the user was clearly informed of the requirements before the contract was concluded. The requirements may be changed only under section 10.',
} as const;
