import fs from 'node:fs';

const read = (path) => fs.readFileSync(path, 'utf8');
const auth = read('components/AuthControls.tsx');
const pricing = read('components/PricingPage.tsx');
const school = read('components/SchoolAdmin.tsx');
const individualApi = read('app/api/billing/stripe/checkout/route.ts');
const schoolApi = read('app/api/organizations/route.ts');
const footer = read('components/SiteFooter.tsx');
const proxy = read('proxy.ts');
const terms = read('app/terms/page.tsx');
const legal = read('lib/legal.ts');
const gdpr = read('app/gdpr/page.tsx');
const dpa = read('lib/dpa-document.ts');
const termsAuditMigration = read('supabase/migrations/20260921033344_add_terms_acceptance_audit.sql');
const contractSnapshot = read('lib/individual-contract-snapshot.ts');
const contractSnapshotMigration = read('supabase/migrations/20260921045117_add_individual_contract_snapshots.sql');
const contractLinkMigration = read('supabase/migrations/20260921045911_atomically_link_individual_contract_snapshot.sql');

const fail = (message) => { throw new Error('[terms] ' + message); };

if (!footer.includes('/terms')) fail('footer must link to Terms');
if (!proxy.includes("pathname === '/terms'")) fail('/terms must use locale gateway');
if (!auth.includes('termsAccepted') || !auth.includes('terms_acceptance_version')) fail('registration must require and record Terms acceptance');
if (!pricing.includes('termsAccepted') || !pricing.includes('immediatePerformanceRequested')) fail('individual paid checkout must require Terms and immediate-service request');
if (!individualApi.includes('termsAccepted: z.literal(true)') || !individualApi.includes('immediatePerformanceRequested: z.literal(true)')) fail('individual checkout server must fail closed without acceptance');
if (!individualApi.includes("locale: z.enum(['cs', 'en'])")) fail('individual checkout must bind the contract snapshot language');
if (!individualApi.includes('create_and_link_individual_contract_snapshot')) fail('individual checkout must persist immutable contract evidence before returning the payment URL');
if (!individualApi.includes('contract_snapshot_store_failed')) fail('individual checkout must fail closed when immutable contract evidence cannot be stored');
if (!individualApi.includes('contractSnapshotId: snapshotId')) fail('Stripe checkout must carry the immutable contract snapshot ID');
if (!school.includes('termsAccepted') || !schoolApi.includes('termsAccepted: z.literal(true)')) fail('school ordering must require Terms on client and server');
if (!school.includes('DPA_ACCEPTANCE_KEY') || !school.includes('/dpa')) fail('school ordering must explicitly present and bind the DPA');
if (!schoolApi.includes('dpaAccepted: z.literal(true)') || !schoolApi.includes('dpaAcceptanceKey: z.literal(DPA_ACCEPTANCE_KEY)')) fail('school ordering server must fail closed without the active DPA');
if (!schoolApi.includes('dpaVersion: DPA_VERSION') || !schoolApi.includes('dpaAcceptanceKey: input.dpaAcceptanceKey')) fail('school order snapshot must record the accepted DPA version and key');
if (!legal.includes("TERMS_ACCEPTANCE_KEY = '2026-09-21-v1'")) fail('shared Terms acceptance version key is missing');
if (!legal.includes("DPA_VERSION = '1.0'") || !legal.includes("DPA_ACCEPTANCE_KEY = '2026-09-21-dpa-v1'")) fail('shared DPA version and acceptance key are missing');
if (!dpa.includes('Výmaz nebo vrácení dat') || !dpa.includes('Deletion or return of data') || !dpa.includes('Informace a audit') || !dpa.includes('Information and audits')) fail('DPA must cover Article 28 deletion/return and audit duties');
if (!auth.includes('TERMS_ACCEPTANCE_KEY') || !pricing.includes('TERMS_ACCEPTANCE_KEY') || !school.includes('TERMS_ACCEPTANCE_KEY')) fail('client flows must use the shared Terms acceptance key');
if (!individualApi.includes('TERMS_ACCEPTANCE_KEY') || !schoolApi.includes('TERMS_ACCEPTANCE_KEY')) fail('server flows must use the shared Terms acceptance key');
if (!schoolApi.includes('acceptedByUserId: userId')) fail('school Terms acceptance must record the accepting account');
if (!terms.includes('88878431') || !terms.includes('289 24 Milovice – Mladá') || !terms.includes('14') || !terms.includes('coi.gov.cz')) fail('Terms page is missing provider or consumer-rights essentials');
const auditTableDefinition = termsAuditMigration.match(/create table private\.terms_acceptance_events \(([\s\S]*?)\n\);/)?.[1] ?? '';
if (!auditTableDefinition || auditTableDefinition.includes('references auth.users')) fail('Terms audit must survive account deletion and must not cascade through auth.users');
if (!termsAuditMigration.includes('alter table private.terms_acceptance_events enable row level security')) fail('Terms audit table must have RLS enabled');
if (!termsAuditMigration.includes('revoke all on table private.terms_acceptance_events from public, anon, authenticated')) fail('Terms audit table must not be client-accessible');
if (!termsAuditMigration.includes('terms_acceptance_events_append_only') || !termsAuditMigration.includes("raise exception 'terms acceptance audit is append-only'")) fail('Terms audit must be append-only');
if (!termsAuditMigration.includes("current_terms_version constant text := '1.0'") || !termsAuditMigration.includes("current_terms_acceptance_key constant text := '2026-09-21-v1'")) fail('database Terms audit constants must match the active Terms version');
if (!termsAuditMigration.includes('requested_terms_acceptance and requested_terms_acceptance_key = current_terms_acceptance_key')) fail('signup audit must only mirror explicit acceptance of the active Terms key');
if (!contractSnapshot.includes("TERMS_VERSION !== '1.0'") || !contractSnapshot.includes("TERMS_ACCEPTANCE_KEY !== '2026-09-21-v1'")) fail('immutable contract builder must hard-pin the supported Terms version');
if (!contractSnapshot.includes('88878431') || !contractSnapshot.includes('289 24 Milovice – Mladá') || !contractSnapshot.includes('Vzorový formulář pro odstoupení') || !contractSnapshot.includes('Model withdrawal form')) fail('immutable contract documents must include provider and withdrawal essentials');
if (!contractSnapshot.includes("createHash('sha256')") || !contractSnapshot.includes('--syllonaut-withdrawal-form--')) fail('immutable contract documents must carry a deterministic integrity hash');
const snapshotTableDefinition = contractSnapshotMigration.match(/create table private\.individual_contract_snapshots \(([\s\S]*?)\n\);/)?.[1] ?? '';
if (!snapshotTableDefinition || snapshotTableDefinition.includes('references auth.users')) fail('paid contract evidence must survive account deletion and must not cascade through auth.users');
if (!contractSnapshotMigration.includes('individual_contract_snapshots_append_only') || !contractSnapshotMigration.includes('individual contract evidence is append-only')) fail('paid contract evidence must be append-only');
if (!contractSnapshotMigration.includes('enable row level security') || !contractSnapshotMigration.includes('revoke all on table private.individual_contract_snapshots from public, anon, authenticated')) fail('paid contract evidence must not be client-readable');
if (!contractLinkMigration.includes('individual_contract_checkout_links_append_only')) fail('Stripe checkout linkage must be append-only');
if (!contractLinkMigration.includes('create_and_link_individual_contract_snapshot')) fail('contract snapshot and checkout linkage must be atomic');
if (!contractLinkMigration.includes('get_individual_contract_snapshot_for_delivery')) fail('activation email must have a scoped service-only evidence lookup');
if (!contractLinkMigration.includes('grant execute on function public.get_individual_contract_snapshot_for_delivery') || !contractLinkMigration.includes('to service_role')) fail('contract evidence delivery lookup must remain service-role only');
if (!gdpr.includes('Potvrzení placené individuální smlouvy:') || !gdpr.includes('Paid individual contract evidence:') || !gdpr.includes('Neměnný snapshot placené individuální smlouvy') || !gdpr.includes('immutable paid individual contract snapshot')) fail('privacy notice must disclose immutable paid-contract evidence and retention');
if (!gdpr.includes('Souhlas s obchodními podmínkami:') || !gdpr.includes('Terms acceptance:') || !gdpr.includes('právních nároků') || !gdpr.includes('legal claims')) fail('privacy notice must disclose Terms acceptance audit and retention');
console.log('Terms acceptance contract OK');
